### ISSUE TITLE
node 的版本是多少?

### ISSUE THREAD

**Issue by zzzzbbbxxx** [tangyiming/artemis-fe#9]
该项目使用的node和nvm分别是哪一个版本? 将代码下载后，执行 npm install 失败了。我本地使用的是 node 12.16.1 和 npm 6.13.4

**Comment by tangyiming** [comment]
> 该项目使用的node和nvm分别是哪一个版本? 将代码下载后，执行 npm install 失败了。我本地使用的是 node 12.16.1 和 npm 6.13.4

试试10.x.x 正常来说12也是可以的

**Comment by tangyiming** [comment]
```
C:\Users\eamon>node -v
v10.24.1

C:\Users\eamon>npm -v
6.14.12
```

今天用以上版本试了下，直接npm install 是可以成功的，你试试看。

npm源就是默认的：`npm config set registry https://registry.npmjs.org`
